version: '3'
services:
  web:
    image: node:11.9-alpine
    depends_on:
      - mongo
    environment:
      SSL_ENABLED: "false"
    volumes:
      - ..:/usr/src/service
    working_dir: /usr/src/service
    command: npm run start
    ports:
      - 3000:3000
    restart: on-failure
  mongo:
    image: mongo
    restart: always
    ports:
      - 4001:27017
    volumes:
    - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 3001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
